name: "CI"

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Python, pipenv and Pipfile packages
      uses: palewire/install-python-pipenv-pipfile@v2
      with:
        python-version: 3.9

    - run: ./bundle.sh

    - name: Release Plugin
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: browser-playerctl
        automatic_release_tag: continuous
        prerelease: true
        draft: false
        files: |
          browser-playerctl.zip
        repo_token: ${{ secrets.GITHUB_TOKEN }}
